myFruitList = ['Apple', 'Banana', 'Cherry']
print(myFruitList)
print(type(myFruitList))
print(myFruitList[0])
print(myFruitList[1])
print(myFruitList[2])
myFruitList[2] = 'Orange'
print(myFruitList)
myFinalAnswerTuple = ('Apple', 'Banana', 'Pneapple')
print(myFinalAnswerTuple)
print(type(myFinalAnswerTuple))
print(myFinalAnswerTuple[0])
print(myFinalAnswerTuple[1])
print(myFinalAnswerTuple[2])
myFavouriteDictionary = {'Akua':'Apple', 'Saanvi':'Banana', 'Paulo':'Pineapple'}
print(myFavouriteDictionary)
print(type(myFavouriteDictionary))
print(myFavouriteDictionary['Akua'])
print(myFavouriteDictionary['Saanvi'])
print(myFavouriteDictionary['Paulo'])